[time]
disabled = false
format = '[\[ $time \]]($style) '
time_format = "%T"

[cmd_duration]
min_time = 500
format = "took [$duration](bold yellow)"

[nodejs]
disabled = true

[battery]
disabled = true

[package]
disabled = true

[git_branch]
symbol = "🌱 "

[git_status]
disabled = true

[lua]
disabled = true